apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: ata-meetup-deployment
    labels:
        app: ata-meetup
spec:
  selector:
    matchLabels:
      app: ata-meetup
  replicas: 2
  template:
    metadata:
      labels:
        app: ata-meetup
    spec:
      containers:
      - name: ata-meetup
        image: pdincau/ata-meetup:1
        ports:
        - containerPort: 8080

